### ISSUE TITLE
Spec name and API short name

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-sink-metadata-processing#78] opened 2021-12-17 10:46 UTC
Flow Compatibility Management is a good name.
_/x-nmos/fcm_ is somehow not as memorable.

Other NMOS APIs, even ones with long-winded names like Audio Channel Mapping so far decided not to use initialisms, so I'm just wondering if _/x-nmos/flowcompatibility_ or something would be better?

Hm, it is _Flow_ compatibility we're talking about here, not _Stream_ compatibility, is it?? 🤔

**Comment by alabou** [comment] 2021-12-17 18:09
In NMOS a Flow describes a stream ... so IS-11 is about Flow ... the Flow produces by a Sender ... such Flow is also described by the SDP transport file produced by the Sender ... on the Receiver side, as there is no Flow object associated to a Receiver in NMOS we can still state that internally the Receiver infer a Flow from the SDP transport file.

**Comment by garethsb** [comment] 2021-12-17 18:31
Not quite. A Flow is transport-agnostic. A stream is a Flow transmitted over a specific transport by a Sender.

**Comment by alabou** [comment] 2021-12-17 18:54
Thanks for the precision, so a Flow describes the transport agnostic parameters of a stream ... IS-11 is still about Flows as far as I can tell ...

**Comment by garethsb** [comment] 2021-12-17 19:02
Thanks for quick and thorough responses, Alain. 

>  IS-11 is still about Flows as far as I can tell ...

If that's the case, so for example the constraint sets will never be used to express transport parameter constraints only format constraints, then the name seems accurate.

**Comment by alabou** [comment] 2021-12-17 21:06
I think it is a safe assumption because IS-05 already support the concept with the "contraints" and "transport_params" endpoints for both senders and receivers.

**Comment by garethsb** [comment] 2021-12-17 21:57
There can be more to transport constraints than covered by IS-05. There are a few transport parameter constraints already defined for use with BCP-004-01 in an IS-04 Receiver.

https://specs.amwa.tv/nmos-parameter-registers/branches/main/capabilities

**Comment by alabou** [comment] 2021-12-17 23:37
It seems strange to have transport capabilities that are in receiver capabilities ("caps") instead of IS-05 receiver "constraints" ... Ideally new transport constraints should be expressed in the "constraints" endpoint but I see that some have landed in the receiver capabilities. Then I'm wondering if being strict in using the word Flow would implies not allowing transport capabilities/constraints for IS-11 is a good idea ...

**Comment by garethsb** [comment] 2021-12-18 08:58
You're right, it seems a little strange. I think there is a subtle difference between the IS-04 Receiver caps and the IS-05 Receiver constraints, that has influenced where each one lands. The latter are constraining transport parameters that need to be set on the Receiver in order to connect to the stream at all. The former are indicating constraints on the properties of a supported stream itself. This is worth discussing more.

> I'm wondering if being strict in using the word Flow would implies not allowing transport capabilities/constraints for IS-11 is a good idea ...

Right. If that strictness is intentional, Flow is good. If not, I wondered whether Stream Compatibility Management was better.

**Comment by N-Nagorny** [comment] 2022-01-12 06:47
I'm in favor of `/x-nmos/fcm` -> `/x-nmos/flowcompatibility` replacement. What do you guys think about leaving `urn:x-nmos:control:fcm/v1.0` for Device control type? I can't catch common logic in existing ones to be honest. https://specs.amwa.tv/nmos-parameter-registers/branches/main/device-control-types/

**Comment by garethsb** [comment] 2022-01-12 07:06
Agreed, the existing URN values for the Connection API, Events API and Channel Mapping API don't seem to follow a consistent pattern. The only vaguely consistent option I could come up with would be `fc-ctrl` maybe?

Since you keep Flow rather than Stream in the name, please would you mind explaining why transport parameter constraints are out of scope for IS-11?

**Comment by alabou** [comment] 2022-01-13 16:24
"Since you keep Flow rather than Stream in the name, please would you mind explaining why transport parameter constraints are out of scope for IS-11?"

If we forget about the name "Flow" versus "Stream" and the fact that constraints on the receiver side are both expressed at the IS-05 level and IS-04 level ... There is nothing in IS-11 preventing that those receiver capabilities that relate to transport could be considered by IS-11 ... It is just that I thing it is not worth changing the name from Flow to Stream because of that. I would keep the Flow name because most of the receiver capabilities are format related and allow IS-11 to operate on all the possible receiver capabilities. If IS-11 was designed before those transport capabilities were added ... there would be no issue with the Flow name and the additional constraints would nicely be considered by IS-11 ...

What is your opinion?

**Comment by garethsb** [comment] 2022-01-17 08:42
I still have the impression that this spec is about negotiating what's transmitted between a Sender and a Receiver. While in network terminology this is usually called a flow, the IS-04 Flow is transport agnostic and we usually talk about streams, e.g. see BCP-004-01. I think this spec could be called something like Stream Negotiation, but I appreciate that I appear to be a lone voice!

**Comment by garethsb** [comment] 2022-01-17 17:06
Another suggestion, Connection Negotiation. (Which reminds me that the URN for the Connection API, that is `sr-ctrl`, probably stood for Sender/Receiver Control?)

**Closed as completed** 2022-04-04 14:21 UTC
